In [151]:
import requests
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [152]:
r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?q=sunflowers')
res = r.json()

In [153]:
sunflower_ids = res['objectIDs']

In [154]:
sunflower_ids

[436524,
 484935,
 437112,
 210191,
 431264,
 397949,
 656530,
 480725,
 486590,
 485308,
 375281,
 705155,
 11922,
 2032,
 343052,
 20141,
 347980,
 2019,
 208554,
 403496,
 437115,
 207869,
 360837,
 400581,
 423400,
 707887,
 223828,
 682927,
 57922,
 79739,
 193938,
 339347,
 649813,
 208218,
 202228,
 437984,
 436534,
 761604,
 437329,
 436252,
 363282,
 207753,
 822570,
 816522,
 487043,
 436580,
 437526,
 203893,
 367434,
 190739,
 423237,
 262423,
 839296,
 367817,
 822590,
 822589,
 13644,
 18362,
 820022,
 648617,
 892559,
 761731,
 814626,
 207967,
 626832,
 701016,
 262430,
 262428,
 841928,
 707697,
 205386,
 262378,
 426804,
 633526,
 369073,
 747779,
 436529,
 852414,
 427872,
 895564,
 436530,
 436535,
 436121,
 724844,
 436144,
 437980,
 631808,
 834580,
 834585,
 834765]

In [155]:
number = [436524,
2032,
20149,
437329,
16822570]

In [156]:
new_list = []
for i in number:
    if i in sunflower_ids:
        new_list.append(i)

In [157]:
r_test = requests.get(f'https://collectionapi.metmuseum.org/public/collection/v1/objects/437980')
obj_test = r_test.json()

In [158]:
df = pd.DataFrame.from_dict(obj_test, orient='index')

In [159]:
df

                                                                       0
objectID                                                          437980
isHighlight                                                        False
accessionNumber                                                    49.30
accessionYear                                                       1949
isPublicDomain                                                      True
primaryImage           https://images.metmuseum.org/CRDImages/ep/orig...
primaryImageSmall      https://images.metmuseum.org/CRDImages/ep/web-...
additionalImages                                                      []
constituents           [{'constituentID': 161947, 'role': 'Artist', '...
department                                            European Paintings
objectName                                                      Painting
title                                                          Cypresses
culture
period
dynasty
reign
portfolio
artistRole                                                        Artist
artistPrefix
artistDisplayName                                       Vincent van Gogh
artistDisplayBio                Dutch, Zundert 1853â€“1890 Auvers-sur-Oise
artistSuffix
artistAlphaSort                                        Gogh, Vincent van
artistNationality                                                  Dutch
artistBeginDate                                                     1853
artistEndDate                                                       1890
artistGender
artistWikidata_URL                   https://www.wikidata.org/wiki/Q5582
artistULAN_URL                http://vocab.getty.edu/page/ulan/500115588
objectDate                                                          1889
objectBeginDate                                                     1889
objectEndDate                                                       1889
medium                                                     Oil on canvas
dimensions                            36 3/4 x 29 1/8 in. (93.4 x 74 cm)
measurements           [{'elementName': 'Overall', 'elementDescriptio...
creditLine                                             Rogers Fund, 1949
geographyType
city
state
county
country
region
subregion
locale
locus
excavation
river
classification                                                 Paintings
rightsAndReproduction
linkResource
metadataDate                                      2023-02-28T04:47:13.3Z
repository                      Metropolitan Museum of Art, New York, NY
objectURL              https://www.metmuseum.org/art/collection/searc...
tags                   [{'term': 'Landscapes', 'AAT_URL': 'http://voc...
objectWikidata_URL                 https://www.wikidata.org/wiki/Q867510
isTimelineWork                                                      True
GalleryNumber                                                        825

In [160]:
dfs = []
for i in sunflower_ids:
    r_test = requests.get(f'https://collectionapi.metmuseum.org/public/collection/v1/objects/{i}')
    obj_test = r_test.json()
    if all(field in obj_test for field in ['objectID', 'title', 'artistDisplayName', 'department', 'objectBeginDate', 'objectEndDate', 'period', 'objectName', 'culture']):
        df = pd.DataFrame.from_dict(obj_test, orient='index') \
        .loc[['objectID', 'title', 'artistDisplayName', 'department', 'objectBeginDate', 'objectEndDate', 'period', 'objectName', 'culture']]
        df = df.transpose()
        df = df.set_index('objectID')
        dfs.append(df)

In [161]:
result_df = pd.concat(dfs)

In [162]:
result_df[result_df['culture'] == 'Japan']

,title,artistDisplayName,department,objectBeginDate,objectEndDate,period,objectName,culture
objectID,,,,,,,,
57922,Incense box,,Asian Art,1700,1799,Edo period (1615â€“1868),Incense box,Japan

In [163]:
r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?departmentId=6&q=cat')
cats = r.json()

In [164]:
cat_ids = cats['objectIDs']

In [165]:
cat_ids[:3]

[49698, 49470, 53222]